### ISSUE TITLE
As a developer, I want to have the 1.9 image of esn_sabre when I use openpaas-platform-docker-dev

### ISSUE THREAD

**Issue by MichaelBailly** [linagora/openpaas-platform-docker-dev#3]
Use the image https://docker-registry.linagora.com/harbor/projects/15/repositories/openpaas-snapshots%2Fopenpaas-esn-sabre/tags/1.9

**Comment by alagane** [comment]
Related merge request: https://ci.linagora.com/linagora/lgs/openpaas/openpaas-platform-docker-dev/merge_requests/61
